pull_request_rules:
   - name: Automatic merge for Dependabot pull requests
     conditions:
       - "author~=^dependabot(|-preview).*$"
       - "base=master"
     actions:
       merge:
         method: merge
#  pull_request_rules:
#    - name: Automatic close for Dependabot pull requests
#      conditions:
#        - "author~=^dependabot(|-preview).*$"
#        - "#status-failure>1"
#        - "base=master"
#      actions:
#        merge:
#          method: close
 pull_request_rules:
   - name: Automatic merge for ImgBot pull requests
     conditions:
       - "author=imgbot[bot]"
       - "base=master"
     actions:
       merge:
         method: merge
