pull_request_rules:
   - name: Automatic merge for Dependabot pull requests
     conditions:
       - "author~=^dependabot(|-preview).*$"
       - "base=master"
     actions:
       merge:
         method: merge
