name = "clickhouse-website-production"
type = "webpack"
account_id = "d4fd593eebab2e3a58a599400c4cd64d"
workers_dev = true
webpack_config = "webpack.config.js"
kv-namespaces = [
	 { binding = "RATING", id = "fab071214bbc4bc8bce73f8986701aec" },
	 { binding = "RATING_PER_IP", id = "fab071214bbc4bc8bce73f8986701aec" }
]

[env.production]
route = "clickhouse.tech/*"
zone_id = "4fc6fb1d46e87851605aa7fa69ca6fe0"