import { addDefaultHeaders } from './util';


const html = `<!DOCTYPE html>
<body>
  <h1>Hello World</h1>
  <p>This markup was generated by a Cloudflare Worker.</p>
</body>`;

export async function handleDebugRequest(request: Request) {
  const response = new Response(html, {
    headers: {
      'content-type': 'text/html;charset=UTF-8',
    },
  })

  addDefaultHeaders(response);
  response.headers.set(
    'Access-Control-Allow-Origin',
    '*'
  );
  response.headers.set(
    'Access-Control-Allow-Methods',
    'POST, PUT, GET, OPTIONS'
  );
  return response;
}
